# Generated by Django 4.2.9 on 2026-01-26 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('food_type', models.CharField(choices=[('prepared', 'Prepared Food'), ('packaged', 'Packaged Goods'), ('produce', 'Fresh Produce'), ('dairy', 'Dairy Products'), ('bakery', 'Bakery Items'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.CharField(help_text="e.g., '5 plates', '2 kg', '10 items'", max_length=100)),
                ('expiry_date', models.DateTimeField()),
                ('pickup_location', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('dietary_tags', models.CharField(blank=True, help_text="e.g., 'vegetarian, gluten-free'", max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='listings_fo_status_92d96a_idx'), models.Index(fields=['food_type'], name='listings_fo_food_ty_ae6b40_idx')],
            },
        ),
    ]
