# Generated by Django 4.2.9 on 2026-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for pickup coordination', max_length=20),
        ),
    ]
