# Generated by Django 4.2.9 on 2026-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_foodlisting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='phone_number',
            field=models.CharField(help_text='Contact number for pickup coordination', max_length=20),
        ),
    ]
