# Generated by Django 4.2.9 on 2026-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_foodlisting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
